version: "3.9"

services:
  db:
    image: postgres:13
    container_name: db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build:
      context: .
      args:
        - workdir=$WORKDIR
    container_name: web_container
    env_file:
      - .env
    depends_on:
      - db

volumes:
    postgres_data:
        external: true
