version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - .env

  web:
    build:
      context: .
      args:
        - config=production
        - workdir=$WORKDIR
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - staticfiles:/opt/app/staticfiles
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build: ./src
    volumes:
      - staticfiles:/opt/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
    postgres_data:
        external: true
    staticfiles:
